In [2]:
import pandas as pd
df =pd.read_csv('dataSet/dataset.csv')

In [3]:
for i in df.columns:
    if "apache" in i:
        print(i)

apache_2_diagnosis
apache_3j_diagnosis
apache_post_operative
arf_apache
gcs_eyes_apache
gcs_motor_apache
gcs_unable_apache
gcs_verbal_apache
heart_rate_apache
intubated_apache
map_apache
resprate_apache
temp_apache
ventilated_apache
apache_4a_hospital_death_prob
apache_4a_icu_death_prob
apache_3j_bodysystem
apache_2_bodysystem

In [4]:
#删除数据集中的apache_4a_hospital_death_prob，apache_4a_icu_death_prob列，然后保存数据集
df.drop(['apache_4a_hospital_death_prob', 'apache_4a_icu_death_prob'], axis=1, inplace=True)
# df.to_csv('dataSet/dataset_processed.csv', index=False)

In [5]:
top_features = ['solid_tumor_with_metastasis', 'd1_sysbp_noninvasive_min', 'gcs_eyes_apache', 'apache_3j_diagnosis', 'apache_3j_bodysystem', 'd1_sysbp_min', 'elective_surgery', 'ventilated_apache', 'gcs_motor_apache']
target_feature = 'hospital_death'
#查找target_feature 为1时 top_features 的值
df_target_1 = df[df[target_feature] == 1]
df_target_1[top_features].describe()

,solid_tumor_with_metastasis,d1_sysbp_noninvasive_min,gcs_eyes_apache,apache_3j_diagnosis,d1_sysbp_min,elective_surgery,ventilated_apache,gcs_motor_apache
count,7830.000000,7807.000000,7586.000000,7786.000000,7884.000000,7915.000000,7830.000000,7586.000000
mean,0.044317,82.831494,2.649222,421.149669,82.766362,0.065824,0.674968,4.273135
std,0.205811,22.423200,1.308437,372.007242,22.400673,0.247991,0.468417,2.071181
min,0.000000,41.030000,1.000000,0.180000,41.000000,0.000000,0.000000,1.000000
25%,0.000000,68.000000,1.000000,107.010000,68.000000,0.000000,0.000000,1.000000
50%,0.000000,82.000000,3.000000,401.010000,82.000000,0.000000,1.000000,5.000000
75%,0.000000,96.000000,4.000000,501.050000,96.000000,0.000000,1.000000,6.000000
max,1.000000,160.000000,4.000000,2201.050000,160.000000,1.000000,1.000000,6.000000

In [7]:
df_target_1[top_features].head(20)

,solid_tumor_with_metastasis,d1_sysbp_noninvasive_min,gcs_eyes_apache,apache_3j_diagnosis,apache_3j_bodysystem,d1_sysbp_min,elective_surgery,ventilated_apache,gcs_motor_apache
8,0.0,98.0,4.0,103.01,Cardiovascular,98.0,0,1.0,6.0
25,0.0,74.0,4.0,501.06,Sepsis,74.0,0,1.0,6.0
46,1.0,NaN,1.0,1502.02,Neurological,41.0,0,1.0,3.0
58,0.0,86.0,4.0,207.01,Respiratory,86.0,0,0.0,6.0
73,0.0,66.0,4.0,802.04,Hematological,66.0,0,0.0,6.0
77,0.0,87.0,4.0,501.05,Sepsis,87.0,0,0.0,6.0
112,0.0,113.0,2.0,403.01,Neurological,113.0,0,1.0,3.0
128,0.0,88.0,NaN,1904.01,Musculoskeletal/Skin,88.0,1,1.0,NaN
129,0.0,91.0,4.0,206.01,Respiratory,91.0,0,1.0,6.0
134,0.0,148.0,4.0,403.01,Neurological,148.0,0,0.0,6.0
164,0.0,90.0,3.0,501.05,Sepsis,90.0,0,1.0,5.0
182,0.0,96.0,1.0,703.03,Metabolic,96.0,0,1.0,1.0
200,0.0,48.0,1.0,501.05,Sepsis,48.0,0,1.0,4.0
202,0.0,111.0,4.0,401.01,Neurological,111.0,0,1.0,6.0
291,1.0,68.0,4.0,501.06,Sepsis,68.0,0,0.0,6.0
298,0.0,107.0,1.0,102.01,Cardiovascular,107.0,0,1.0,1.0
302,0.0,87.0,1.0,102.01,Cardiovascular,87.0,0,1.0,1.0
307,0.0,87.0,1.0,403.01,Neurological,87.0,0,1.0,1.0
343,0.0,71.0,4.0,501.05,Sepsis,71.0,0,1.0,6.0
378,1.0,75.0,3.0,501.02,Sepsis,75.0,0,1.0,6.0